# Generated by Django 3.1.2 on 2020-10-31 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='author',
            new_name='SensorNode',
        ),
    ]
